beacon_gps:
  ros__parameters:
    frequency: 5.0
    port: /dev/hc12
    baud: 9600
<<<<<<< HEAD
    frame_id: gps_beacon
=======
    frame_id: gps
>>>>>>> upstream/dev
    useRMC: false  #false is GGA
